import os

os.system("scrapy crawl 90min")
os.system("scrapy crawl abola")
os.system("scrapy crawl bbc")
os.system("scrapy crawl besoccer")
os.system("scrapy crawl bleacherreport")
os.system("scrapy crawl dailystar")
os.system("scrapy crawl depor")
os.system("scrapy crawl diarioas")
os.system("scrapy crawl dn")
os.system("scrapy crawl ecodiario")
os.system("scrapy crawl eldesmarque")
os.system("scrapy crawl elpais")
os.system("scrapy crawl espn") #the scrapy works, but much unralated text is retrieved.
os.system("scrapy crawl estadiodeportivo")
os.system("scrapy crawl express")
os.system("scrapy crawl fcbn")
os.system("scrapy crawl fichajes.com")
os.system("scrapy crawl fichajes.net")
os.system("scrapy crawl footballespana")
os.system("scrapy crawl foxsports")
os.system("scrapy crawl futebol365")
os.system("scrapy crawl goal")
os.system("scrapy crawl hitc")
os.system("scrapy crawl maisfutebol")
os.system("scrapy crawl marca")
os.system("scrapy crawl metro")
os.system("scrapy crawl mundodeportivo")
os.system("scrapy crawl noticiasaominuto") #the scrapy works, but much unralated text is retrieved.
os.system("scrapy crawl ojogo")
os.system("scrapy crawl record")
os.system("scrapy crawl sapo")
os.system("scrapy crawl skysports")
os.system("scrapy crawl sport")
os.system("scrapy crawl superdeporte")
os.system("scrapy crawl talksport")
os.system("scrapy crawl teamtalk") #the scrapy works, but much unralated text is retrieved.
os.system("scrapy crawl telegraph")
os.system("scrapy crawl thesun")
#os.system("scrapy crawl zerozero") #recapcha

